### PR TITLE
Fix code block stackoverflow

### PR DESCRIPTION
**Pull request by bodewig**
see #53 

This works for us, but there may be some cases that the changes miss, see the discussion inside the issue itself.

### CODE REVIEW

**Comment by rdmueller** [comment]
Wow. ich komme ja kaum noch hinterher :-)

**Comment by bodewig** [comment]
Let's see what @MoePad says in #53 - I hope merging has not been premature.

Many thanks!

**Comment by MoePad** [comment]
I've just tested it for java and bash code blocks: it works fine! Good work! :)

**Comment by bodewig** [comment]
Thanks!

**Pull request merged**
