### PR TITLE
Added spanish translation for Arc42 Template

### PR DESCRIPTION
**Pull request by isidorotrevino**
I prepared a Spanish version of the Arc42 template so it would be easier to adopt for Latin American and Spanish developers

### CODE REVIEW

**Comment by rdmueller** [comment]
thank you very much for this PR - it is highly appreciated!
Unfortunately, I do not speak spanish.
Would you be willing to maintain the spanish version when there are updates to the english one?

**Comment by isidorotrevino** [comment]
Sure! 

We are implementing the Arc42 template in some projects so it is in our best interest to keep it updated

**Comment by gernotstarke** [comment]
@isidorotrevino Thank you very much!

The correct repository for the translation is the [arc42-template](https://github.com/arc42/arc42-template) repository. We already maintain two languages (DE, EN) there.

Your version is HIGHLY welcome - although currently none of the arc42 maintainers is fluent in Spanish, and therefore we are not able to comment on your translation...

Could you please open a PR there (then your contribution will be clearly visible!).

Alternatively, I might take your PR from HERE and manually move it to the arc42-template...
but then I (Gernot) would be the committer...

kind regards from Cologne, Germany,
Gernot

**Comment by rdmueller** [comment]
Thanx for your contribution!
I merged it for the moment. We are currently planing to refactor docToolchain a bit (see https://github.com/rdmueller/docToolchain/issues/71 for details). 
As mentioned by Gernot, please create another pull request for the main arc42-template repository. A later version of docToolchain will directly fetch the template from this repository.

**Pull request merged**
